Update synthetic elections
usnistgov/cdf-test-method pull request #6
Opened 2023-07-31 15:12 UTC by JDziurlaj

All:
- Stablizes `GeneratedDate` to fixed value

CVR:
- Adds property `CVRContestSelection::OptionPosition`
- Correctly calculates undervotes for contests controlled by a straight party contest
- Adds `CVRContest:Status` when contest is `undervoted` or `overvoted`

ERR:
 - Adds `OtherCounts::Overvotes` and `OtherCounts::Undervotes` at precinct level
 - Removes `VoteCounts` for precincts that do not participate in the contest
 - Changes `ElectionReport::Status` from `unoffical-partial` to `unofficial-complete`

2023-08-25 14:35 UTC, jungshadow requested changes
Impressive and excellent work, @JDziurlaj! Just a few stylistic bits that need a bit of cleanup (e.g., I imagine the table-based layout might have been a straight pandoc translation of the original synthetic Word doc).

2023-08-25 14:35 UTC, jungshadow commented on test_data/real_world/ma/cambridge/2022/general/err_v2/err-2022-11-08-Massachusetts-Cambridge.xml
I just realized that the `err` prefix might seem like an error file to some. I don't have a suggestion, but that just came to mind.

2023-08-25 14:35 UTC, jungshadow commented on test_data/synthetic/gen-01/README.md
> +<li><p>Ranked choice voting: No</p></li>
Why is there a paragraph tag inside the list item? It's not wrong, per se, but seems unnecessary.

2023-08-25 14:35 UTC, jungshadow commented on test_data/synthetic/gen-01/README.md
> +<li></li>
Do these two additional empty list items get rendered?

2023-08-25 14:35 UTC, jungshadow commented on test_data/synthetic/gen-01/README.md
>  <table>
Some of the content here makes sense as a table, but this opening preamble doesn't.

2023-08-25 14:35 UTC, jungshadow commented on test_data/synthetic/prim-01/README.md
> +# NIST Voting Common Data Format Test Method – Test Data
Same comment as the previous file. There's a lot of information that doesn't need to be a part of the table.

2023-08-25 14:35 UTC, jungshadow commented on test_data/synthetic/prim-03/README.md
>  <table>
Same comment as before about the table.

2023-08-25 18:26 UTC, JDziurlaj commented
I can unwrap outer Word table and most of them will get converted to normal GFM tables. However, the one showing the precinct / contest crosswalk will still render as HTML, as apparently GFM doesn't support column spans.

2023-08-29 11:25 UTC, JDziurlaj commented
Removed outer table from ProV&V template. HTML tables were converted to GFM tables for test decks. Ballot definition remains in HTML due to need for colspans.

2023-08-30 11:36 UTC, jungshadow commented
👍 LGTM

2023-08-30 11:38 UTC, merged